name: system_info
version: 4.0.0
homepage: https://sysinfo.onepub.dev
documentation: https://sysinfo.onepub.dev
description: Provides easy access to useful information about the system (architecture, bitness, kernel, memory, operating system, CPU, user).
repository: https://github.com/open-runtime/system_info
environment:
  sdk: ^3.9.0
  
dependencies:
  globbing: ^1.0.0
  path: ^1.9.1
dev_dependencies:
  lint_hard: ^6.0.0
  runtime_common_codestyle:
    git:
      url: https://github.com/open-runtime/runtime_common_codestyle
      tag_pattern: v{{version}}
    version: ^0.1.5
